DATAHUB-100/tooltip
technologiestiftung/next-iot-hub pull request #53
Opened 2021-06-01 13:56 UTC by lucasoeth

- add a line where cursor is
- show y value as tooltip
- show date as tooltip
- add padding above line for better looks

2021-06-01 17:27 UTC, dnsos commented
Hey @vogelino and @lucasoeth, this PR is currently throwing an error in the tests for the `useProjectTokens` hook, even though it wasn't touched. I've encountered this once before and can't quite figure out what's going on there. Do you have an idea?

2021-06-01 19:02 UTC, lucasoeth commented
> Hey @vogelino and @lucasoeth, this PR is currently throwing an error in the tests for the `useProjectTokens` hook, even though it wasn't touched. I've encountered this once before and can't quite figure out what's going on there. Do you have an idea?

Hey @dnsos, I've had this error quite a bit as well. It is reproducible locally but from my testing there is only about a 50% chance of this particular test failing.  I think we should open a ticket because it is def a bug. Sometimes it passes, sometimes it doesn't, and it is frustrating. My suspicion is that it has to do with the msw and mocking. 

If otherwise @dnsos and @vogelino think the PR is good, I would merge it.

2021-06-01 22:09 UTC, vogelino requested changes
Great work overall! The tooltip looks and feels great. Very nice 💪 

I have a few comments though:
- There seems to still be the bug we noticed together. To reproduce it, deactivate mocking and navigate to the following page: http://localhost:3000/27
<img width="958" alt="Screen Shot 2021-06-02 at 12 04 14 AM" src="https://user-images.githubusercontent.com/2759340/120396593-1ce02000-c337-11eb-95d5-15342acdd820.png">

- (optional) I wished the file `LineChart/index.tsx` would be split into chucks each dedicated to a specific purpose. Right now the file is pretty big and will probably keep growing.
- The storybook story for `LineChart` is broken. Please make sure it is fixed before merging. 
- I added some comments with some minimal change requests. Feel free to ignore them if you lack time.

2021-06-01 22:14 UTC, vogelino commented
> > Hey @vogelino and @lucasoeth, this PR is currently throwing an error in the tests for the `useProjectTokens` hook, even though it wasn't touched. I've encountered this once before and can't quite figure out what's going on there. Do you have an idea?
> 
> Hey @dnsos, I've had this error quite a bit as well. It is reproducible locally but from my testing there is only about a 50% chance of this particular test failing. I think we should open a ticket because it is def a bug. Sometimes it passes, sometimes it doesn't, and it is frustrating. My suspicion is that it has to do with the msw and mocking.
> 
> If otherwise @dnsos and @vogelino think the PR is good, I would merge it.

I have had this issue too and I'm quite annoyed by it too. I've been kind of lazy to fix it but we should definitively do that soon! 😄  I'll have a look tomorrow!

2021-06-02 09:22 UTC, dnsos reviewed
Very nice work, @lucasoeth. This feature is an important addition and I like the implementation.

I also think that the `LineChart` component could be split into more pieces, e.g. separating all the tooltip stuff away from it.

Only commenting here, instead of approving, because of the open issues that @vogelino mentioned. After that we're good to go!

2021-06-02 09:22 UTC, dnsos commented on package.json
> +    "@visx/event": "^1.7.0",
It's a good idea to pin dependencies already when adding them. Can be achieved with setting `save-exact = true` in your NPM config.

2021-06-02 11:50 UTC, vogelino approved these changes

2021-06-02 12:21 UTC, dnsos approved these changes
👍

2021-06-02 12:39 UTC, merged

2022-03-29 12:09 UTC, tsboter commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/technologiestiftung/stadtpuls-frontend/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: